namespace AlphaPoint.Api.Models
{
    /// <summary>
    /// Represents the type of the message.
    /// </summary>
    /// <remarks>
    /// Message types 1 (reply), 3 (event), and 5 (error) are generated by the server.
    /// </remarks>
    public enum MessageType
    {
        /// <summary>
        /// Request.
        /// </summary>
        Request = 0,

        /// <summary>
        /// Reply.
        /// </summary>
        Reply = 1,

        /// <summary>
        /// Subscribe to event.
        /// </summary>
        SubscribeToEvent = 2,

        /// <summary>
        /// Event.
        /// </summary>
        Event = 3,

        /// <summary>
        /// Unsubscribe from event.
        /// </summary>
        UnsubscribeFromEvent = 4,

        /// <summary>
        /// Error.
        /// </summary>
        Error = 5
    }
}
